# Generated by Django 4.0 on 2023-11-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_box_storage_order_box_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='city',
            field=models.CharField(blank=True, max_length=25, verbose_name='Город склада'),
        ),
    ]
