# Generated by Django 4.0 on 2023-11-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    def change_images(apps, _):
        Storage = apps.get_model("storage", "Storage")
        Storage.objects.all().update(image='default.png')

    dependencies = [
        ('storage', '0004_box_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото склада'),
        ),
        migrations.RunPython(change_images),
        migrations.AlterField(
            model_name='storage',
            name='feature',
            field=models.CharField(max_length=25, verbose_name='Особенность склада'),
        ),
    ]
