# Generated by Django 4.0 on 2023-11-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_storage_image_alter_storage_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='need_call',
            field=models.BooleanField(default=False, verbose_name='Нужно перезвонить'),
        ),
        migrations.AddField(
            model_name='client',
            name='need_invoice',
            field=models.BooleanField(default=False, verbose_name='Нужен счет'),
        ),
    ]
