# Generated by Django 4.0 on 2023-11-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_client_need_call_client_need_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='box',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='storage.box', verbose_name='Бокс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
    ]
